repositoryUrl: https://github.com/dynamsoft-docs/code-parser-docs/blob/master
repository: Dynamsoft/code-parser-docs
docFullPath: https://www.dynamsoft.com/code-parser
firstLevelUrl: /code-parser
docHomePage: /code-parser/introduction/

introduction: /code-parser/introduction/
parameters: /code-parser/parameters/
enumerations: /code-parser/parameters/enum/
parameters-reference: /code-parser/parameters/reference/

programming: /code-parser/programming/

c-cplusplus: /code-parser/programming/c-cplusplus/
c-cplusplus-api-reference: /code-parser/programming/c-cplusplus/api-reference/

c-functions: /code-parser/programming/c-cplusplus/api-reference/c-functions/
cpp-methods: /code-parser/programming/c-cplusplus/api-reference/c-code-parser-class/
c-cplusplus-structs: /code-parser/programming/c-cplusplus/api-reference/structs/

c-cplusplus-release-notes: /code-parser/programming/c-cplusplus/release-notes/

android: /code-parser/programming/android/
android-api: /code-parser/programming/android/api-reference/
android-release-notes: /code-parser/programming/android/release-notes/

dotnet: /code-parser/programming/dotnet/
dotnet_api: /code-parser/programming/dotnet/api-reference/
dotnet_release_notes: /code-parser/programming/dotnet/release-notes/

objectivec-swift: /code-parser/programming/objectivec-swift/
objectivec-swift-api: /code-parser/programming/objectivec-swift/api-reference/
objectivec-swift-release-notes: /code-parser/programming/objectivec-swift/release-notes/

java: /code-parser/programming/java/
java-api: /code-parser/programming/java/api-reference/
java-release-notes: /code-parser/programming/java/release-notes/

javascript: /code-parser/programming/javascript/
javascript-api: /code-parser/programming/javascript/api-reference/
javascript-release-notes: /code-parser/programming/javascript/release-notes/

assets: /code-parser/assets/
edit_icon: /code-parser/assets/img-icon/edit-icon.png
smile_icon: /code-parser/assets/img-icon/icon-smile.png
sad_icon: /code-parser/assets/img-icon/icon-sad.png
dbr_icon: /code-parser/assets/img-icon/icon-dbr.svg
dwt_icon: /code-parser/assets/img-icon/icon-dwt.svg
dnt_icon: /code-parser/assets/img-icon/icon-dnt.svg

release-notes: /code-parser/release-notes/
license-activation: /code-parser/license-activation/

useVersionTree: true

baseurl: "/code-parser"
plugins:
  - jemoji

url: "https://www.dynamsoft.com" # sitemap root

