repositoryUrl: https://github.com/dynamsoft-docs/code-parser-docs/blob/main
repository: dynamsoft-docs/code-parser-docs
docFullPath: https://www.dynamsoft.com/code-parser/docs/core
firstLevelUrl: /code-parser/docs/core/
docHomePage: /code-parser/docs/core/introduction/

introduction: /code-parser/docs/core/introduction/

cpp: /code-parser/docs/server/programming/cplusplus/
cpp_release_notes: /code-parser/docs/server/programming/cplusplus/release-notes/


javascript: /code-parser/docs/js/programming/javascript/
javascript_release_notes: /code-parser/docs/js/programming/javascript/release-notes/

release-notes: /code-parser/docs/core/release-notes/
code_types: /code-parser/docs/core/code-types/

enumerations: /capture-vision/docs/core/enums/
parameters: /capture-vision/docs/core/parameters/
parameters_reference: /capture-vision/docs/core/parameters/reference/
license: /capture-vision/docs/core/license/


assets: /code-parser/docs/core/assets/
edit_icon: /code-parser/docs/core/assets/img-icon/edit-icon.png
smile_icon: /code-parser/docs/core/assets/img-icon/icon-smile.png
sad_icon: /code-parser/docs/core/assets/img-icon/icon-sad.png

useVersionTree: true

baseurl: "/code-parser/docs/core"
plugins:
  - jemoji

url: "https://www.dynamsoft.com" # sitemap root

