# This is a basic workflow to help you get started with Actions

name: Full-Site-Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-main" and "Build-Preview"
  Build-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build and Upload to Prod Env
        run: |
          cd /home/ubuntu
          [ -d DCPDoc ] && rm -rf DCPDoc
          [ ! -d DCPDoc ] && mkdir -p DCPDoc
          [ ! -d code-parser-docs ] && git clone --depth 1 https://github.com/dynamsoft-docs/code-parser-docs.git
          cd code-parser-docs && git pull && cd .. && cp -rfp ./code-parser-docs/* ./DCPDoc/
          cd Docs-Template-Repo && git pull && cd .. && cp -rfp ./Docs-Template-Repo/* ./DCPDoc/
          cd DCPDoc && bundle exec jekyll build
          python3 /home/ubuntu/ftp.py /home/ubuntu/DCPDoc/_site/ ./www.dynamsoft.com/code-parser/docs/ prod

  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Build the site
        run: |
          cd /home/ubuntu
          [ -d DCPDocPreview ] && rm -rf DCPDocPreview
          [ ! -d DCPDocPreview ] && mkdir -p DCPDocPreview
          [ ! -d code-parser-docs-preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/code-parser-docs.git code-parser-docs-preview
          cd code-parser-docs-preview && git pull && cd .. && cp -rfp ./code-parser-docs-preview/* ./DCPDocPreview/
          cd Docs-Template-Repo && git pull && cd .. && cp -rfp ./Docs-Template-Repo/* ./DCPDocPreview/
          sed -i -e "1,3s/blob\/main$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DCPDocPreview/_config.yml
          cd DCPDocPreview && bundle exec jekyll build
      - name: Sync files to Test Env
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DCPDocPreview/_site/
          server-dir: /www.dynamsoft.com/code-parser/docs/
